### ISSUE TITLE
Not Responsive on mobile screen

### ISSUE THREAD

**Issue by sourabhbagrecha** [kimcoder/react-simple-image-slider#1]
![image](https://user-images.githubusercontent.com/27056663/77827752-88c86680-713d-11ea-9a9d-0d583d001d8c.png)
As of now, the slider is not responsive on different screens, and it is not even possible to make provision for that. 
It would be great if we can add the functionality of setting the width & height in percentage(& other formats). Let me know if there is some already existing functionality for the same purpose.
Thank You!

**Comment by kimcoder** [comment]
Hi, 
First of all Thanks your oppinion :)
I have to develop that you said it. ( It means not exist setting for dynamically width & height at now )
I will fix this as soon as possible.
Thanks.

**Comment by kimcoder** [comment]
@sourabhbagrecha
Hi.
It is fixed :)!
You can see this feature 1.0.3 version.
https://www.npmjs.com/package/react-simple-image-slider

Thank you !

**Comment by sourabhbagrecha** [comment]
That's awesome. Thanks!
