### ISSUE TITLE
onClick

### ISSUE THREAD

**Issue by AustineA** [kimcoder/react-simple-image-slider#10]
Please how do i add a click listener to each of the slide. 
Here is the structure of my data, i want to be able to click on each of the slide and have it link to different location.

```
{
    url: require("../../assets/banner.jpg"),
    link: "",
    key: 1,
  }
```

Thanks in advance

**Comment by kimcoder** [comment]
@AustineA, Hi!
Thanks for your opinion :) 
This feature is published at **v1.0.4**!
Please, Update your package version !

https://www.npmjs.com/package/react-simple-image-slider/v/1.0.4
