### ISSUE TITLE
Images shown wrongly oriented on IOS

### ISSUE THREAD

**Issue by Larcis** [kimcoder/react-simple-image-slider#16]
Hi I'm a newbie to web development,
I m trying to use this package with photos taken with an iPhone XR. My site works as expected both in Android and in desktop but when it comes to IOS (the same phone that I took photos with), the photos I used inside the slider shown with a wrong orientation. Until now I tried to delete EXIF data but no luck, I tried to change used image tag with a safe one (https://www.npmjs.com/package/react-fix-image-orientation) but I couldn't.

**Comment by kimcoder** [comment]
@Larcis 
Hi,
SimpleImageSlider is just a library for sliding images ( literally ).
Parsing or Deleting a EXIF data is not feature of SimpleImageSlider.
Thanks 🙏
