### ISSUE TITLE
How can I edit Navigation button CSS?

### ISSUE THREAD

**Issue by Stavya1993** [kimcoder/react-simple-image-slider#19]
My buttons are coming in the middle of the image. How can I edit the margins of the buttons?

**Comment by kimcoder** [comment]
@Stavya1993 
Hi
That feature is not supported yet. 😥
Sorry

**Comment by kimcoder** [comment]
@Stavya1993 Hi,
Please Check this [2.1.0 version](https://www.npmjs.com/package/react-simple-image-slider/v/2.1.0)
```
navSize: number;
navMargin: number;
```

Also, You can confirm example of this feature at https://kimcoder.github.io/react-simple-image-slider/
