### ISSUE TITLE
set start image index

### ISSUE THREAD

**Issue by Denise-David** [kimcoder/react-simple-image-slider#34]
Is it possible to enter the index from which the slider should start?

**Comment by MOIN-AKHTAR** [comment]
Good pakcage but not option for loop and default index image-If you add these feature this package will be awesome for sliders-

**Comment by kimcoder** [comment]
@Denise-David @MOIN-AKHTAR 
Hi guys,
you can set `startIndex` props at  [v2.1.2]( https://www.npmjs.com/package/react-simple-image-slider/v/2.1.2).

Thanks.
