### ISSUE TITLE
How to set positions of NavArrows?

### ISSUE THREAD

**Issue by BearHunter49** [kimcoder/react-simple-image-slider#36]
안녕하세요. 좋은 라이브러리를 만들어주셔서 감사합니다.

하나 건의사항이 있습니다!
NavArrow를 보면 좌, 우 각각 left: 30px, right 30px이 고정되어 있습니다.
하지만 이미지 크기가 100x100 정도로 작아지게 되면 NavArrow가 가운데로 모이게 돼버립니다.

이를 사용자가 지정할 수 있도록 하면 더 좋을것 같습니다!

**Comment by kimcoder** [comment]
@BearHunter49 
안녕하세요. 
건의해주신 점 감사합니다.

말씀하신 기능은 이 버전에서 확인이 가능합니다. [2.1.0 version](https://www.npmjs.com/package/react-simple-image-slider/v/2.1.0)
```
navSize: number;
navMargin: number;
```

또, 아래 예제 사이트에서도 확인을 할 수가 있습니다!
https://kimcoder.github.io/react-simple-image-slider/
