### ISSUE TITLE
onClickNav return only true

### ISSUE THREAD

**Issue by Choyeongdeok** [kimcoder/react-simple-image-slider#37]
onClickNav = (toRight) => {
    console.log(toRight)
}

왼쪽, 오른쪽 클릭 시 둘 다 true가 찍힙니다

**Comment by kimcoder** [comment]
@Choyeongdeok 
안녕하세요. 이슈 제보 감사합니다. 
위 버그는 ```2.0.4```버전에 픽스하였습니다.
감사합니다 :)
https://www.npmjs.com/package/react-simple-image-slider/v/2.0.4
