### ISSUE TITLE
Image slider package is not working

### ISSUE THREAD

**Issue by irfanjs** [kimcoder/react-simple-image-slider#7]
Hello, I am using npm image slider package : npmjs.com/package/react-simple-image-slider

This package has the property : slideDuration and i am using this property in my code. however, it is not working. Rest of the properties are working.

here is the code for this:

```
import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import ReactBootstrap, { Jumbotron, Container, Row, Col, Column, Image, Button } from 'react-bootstrap';
import SimpleImageSlider from "react-simple-image-slider";


class Homepage extends Component {
  render() {
    const images = [
            { url: '../../Assets/images/img_bg_1.jpg' },
            { url: '../../Assets/images/img_bg_2.jpg' },
            { url: '../../Assets/images/img_bg_3.jpg' },
        ];

    return (

      <div>
               <SimpleImageSlider
                   width={896}
                   height={504}
                   images={images}
                   slideDuration={0.1}
               />
           </div>

  );
  }
}

export default Homepage;
```

I am not sure where is the issue. can someone please suggest where i can get the support. ? Thanks

**Comment by kimcoder** [comment]
Can you explain more details? 
Like a '_slideDuration is still working 0.5 sec ( default value )_' or '__Animation doesn't work_'.

**Comment by irfanjs** [comment]
my understanding is , if we provide the 0.5 sec to slideDuration , all slides should slide automatically . if this understanding is correct , then yes , this is the issue. 
i have provided 0.5 sec as value to slideDuration property , but it does not slide automatically. 
please suggest

**Comment by kimcoder** [comment]
I got it. I think you have misunderstood it.
this slider is not play automatically. ( not yet )
sliderDuration property is just decide for animation duration.

You can check here.
https://kimcoder.github.io/demo/react-simple-image-slider/

**Comment by irfanjs** [comment]
ok.. 
but then , is there any property to get automatic behavior ? if not, any workaround ?

**Comment by kimcoder** [comment]
sorry, this feature is not developed.
So It is impossible for getting automatic behavior.

**Comment by irfanjs** [comment]
ok . thanks
