### ISSUE TITLE
Slider's first image does not seem unless you do not click the nav button while entering a page.

### ISSUE THREAD

**Issue by hybtli** [kimcoder/react-simple-image-slider#82]
When you are entering the first time for the page or refreshing, the first image does not seem, like the one below.

![image](https://user-images.githubusercontent.com/102618972/185109426-a489f00c-03bb-4804-9313-f285b5d2946d.png)
<hr/>

However, when you click the nav buttons, after arriving at the first image, it seems, like the one below.

![image](https://user-images.githubusercontent.com/102618972/185110799-5462a9a3-34f2-481d-a537-cba7ae440c3d.png)
<hr/>

Can anyone help?

```javascript
const images = [{ url: file0 }, { url: file1 }, { url: file2 }];

return(
  <>
    <section className="shadow-none p-3 mb-5 rounded d-flex justify-content-center">
            <SimpleImageSlider
               width={896}
               height={504}
               images={images}
               autoPlay
               autoPlayDelay={5}
               showBullets
               showNavs
        />
      </section> 
  </>
) ;       
```

**Comment by marklee1972** [comment]
I encountered the same case.
Does anyone can solve this issue?

**Comment by hybtli** [comment]
First of all, sorry for the late answer. While creating three variables named `file0`, `file1`, and `file2`, I created like that :
```typescript
  const [file0, setFile0] = useState("");
  const [file1, setFile1] = useState("");
  const [file2, setFile2] = useState("");
```
After doing this I solved my issue:
```typescript
  const [file0, setFile0] = useState<string>("");
  const [file1, setFile1] = useState<string>("");
  const [file2, setFile2] = useState<string>("");
  ```
I hope it will solve also your issue 😊

**Comment by hybtli** [comment]
First of all, sorry for the late answer. While creating three variables named `file0`, `file1`, and `file2`, I created like that :
```typescript
  const [file0, setFile0] = useState("");
  const [file1, setFile1] = useState("");
  const [file2, setFile2] = useState("");
```
After doing this I solved my issue:
```typescript
  const [file0, setFile0] = useState<string>("");
  const [file1, setFile1] = useState<string>("");
  const [file2, setFile2] = useState<string>("");
  ```
I hope it will solve also your issue 😊
